services:
  pgsql:
    image: postgres:15.1-alpine
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks: 
      - backend
    ports:
      - 5432:5432

# server name - CloudBeaver Community , login- cbadmin, password - Password1 
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   volumes:
  #     - type: volume
  #       source: pg
  #       target: /var/lib/pgadmin
  #     - type: bind
  #       source: ./1.sample_data
  #       target: /var/lib/pgadmin/storage/admin_example.com

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/clouldbeaver/workspace
    # Useful for connecting to local databases outside of Docker (Mac/Windows)
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pgsql

volumes:
  pgdata:
    external: true
  pg:
    external: true
  cloudbeaver_data:
    external: true
networks:
  backend:
  
# sql query execution order 
# from/join ->  where -> group by -> having -> select -> distinct -> order by -> limit/offset
# so you can't use computed column in select as condition in where clause as it is calcuted after wehere clause.
# but you can use computed column in order by because its executed after select caluse.


# scalar / row-level function -> it applies to each row data and generates one output for that.
# aggregate functions -> rows are collpased to generate summary values. you can't get individual rows.
# window function -> they work on group of rows and instead of collapsing rows they append the data after each row.